### PR TITLE
User Model + Auth service in the making + Small refactoring in the startup folder

### PR DESCRIPTION
**Pull request by paulrods**

### CODE REVIEW

**Comment by frozenfroggie** [comment]
Your credentials to mLab database are visible right now in logfile.log

**Comment by frozenfroggie** [comment]
Thats why I recommended to untrack this file

**Comment by paulrods** [comment]
How if the logfile.log is on .gitignore ...?

**Comment by paulrods** [comment]
Is just a dummy db but still...

**Comment by frozenfroggie** [comment]
Because this file is already commited so git started to track this file and will not stop tracking them even if we add this file to .gitignore

**Comment by frozenfroggie** [comment]
You have to use git rm --cached logfile.log

**Pull request merged**
